# Generated by Django 4.2.10 on 2024-02-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rates',
            name='price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
