# Generated by Django 4.2.10 on 2024-02-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rates_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='telegram_id',
            field=models.IntegerField(default=123456789),
            preserve_default=False,
        ),
    ]
