version: '3.1'

services:
  db:
    image: postgres
    container_name: postgres_ecoaxl
    restart: always
    environment:
      POSTGRES_PASSWORD: ecoaxl123
      POSTGRES_USER: postgres
      POSTGRES_DB: ecoaxl_db
      PGDATA: /var/lib/postgresql/data
    ports:
      - "7777:5432"
    volumes:
      - /home/ubuntu/postgres/data:/var/lib/postgresql/data
